# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("raw_sales_data.csv")

print("Original Records:", len(df))

# Remove duplicates
df = df.drop_duplicates()

# Fill missing sales
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())

# Fill missing customer
df["Customer"] = df["Customer"].fillna("Unknown")

# Fill missing region
df["Region"] = df["Region"].fillna("Unknown")

# Save cleaned data
df.to_csv("cleaned_sales_data.csv", index=False)

# Summary Report
total_sales = df["Sales"].sum()
avg_sales = df["Sales"].mean()
total_orders = len(df)

report = f"""
DATA CLEANING REPORT

Total Orders : {total_orders}
Total Sales  : {total_sales}
Average Sales: {avg_sales}
"""

with open("report.txt","w") as f:
    f.write(report)

print(report)

# Sales by Region Chart
sales_region = df.groupby("Region")["Sales"].sum()

plt.figure(figsize=(8,5))
sales_region.plot(kind="bar")
plt.title("Sales by Region")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("sales_by_region.png")
plt.show()